### ISSUE TITLE
bug in syscall_mman.c munmap()

### ISSUE THREAD

**Issue by neeraj9** [rumpkernel/rumprun#41]
I am trying to port erlang to rumpkernel and faced some weird issues. After much effort and line-by-line debugging via gdb I found a critical bug in rumprun. The munmap() implementation do not match the posix description, or as such based on my understanding. This issue results into very strange memory corruption in the erlang code, which is definitely non-trivial.

The issue will strike when the application code tries to deallocate a portion of the memory earlier allocated via mmap (as in syscall_mman.c), while assuming that the rest of the portion should still be available to the application after the munmap() call. This is not true as per the munmap() implementation, which frees the complete memory segment allocated earlier.

{Snip from my the freenode iirc}

    <neeraj> The implementation of munmap in rumprun/lib/librumprun_base/syscall_mman.c is probably buggy
    <neeraj> the munmap(void *addr, size_t len) just does free(addr) and return 0
    <neeraj> If I read man munmap correctly then only the pages who are in the [addr, addr+len)  range should be deallocated instead of de-allocating the complete allocation pointed by addr
    <neeraj> In this case erlang is doing a tricky mmap alloc/dealloc, while rump's munmap() implementation deallocating the complete alloc done earlier, resulting in erlang use a deallocated memory location.
    <neeraj> This later results into a memory corruption because future allocation allocates the same memory location which is used by erlang.

I spent a small amount of time thinking about a patch and quickly realized that the allocated in lib/libbmk_core/memalloc.c  bmk_memalloc() uses a header for the complete block. In case the user wants to deallocate only a part of the original allocation then moving header around and re-aligning is required and can be tricky at times (should be handled correctly).

**Comment by anttikantee** [comment]
Yea you're correct.  I was hoping no software would do complex stuff like that :/

There are essentially two options:
1) continue backing mmap(MAP_ANON) with malloc, but allocate a management bitmap and free() only when all pages within the region have been free'd
2) use the page allocator for mmap(MAP_ANON).  The downside is that the page allocator only allows map/free in power of 2 sizes (to prevent the memory map from getting overly fragmented).

Given that malloc() for large sizes is directly backed by the page allocator anyway, I'm thinking "2" is a better option for now.  Hmm, I wonder if it's better to add an interface to the page allocator to allow free'ing individual pages, or track the entire mapping within the mmap emulation.  I guess the latter avoids fragmentation, since we preserve knowledge of what the original "object" is.

Thanks for finding this bug.

**Comment by neeraj9** [comment]
In my case there were couple of things which happened and is required to get erlang onto rump.

1. Allocate a big chunk
2. Look at weird alignment and if its not then reallocate a bigger chunk
3. Look at alignment again and if its not perfect the deallocate two blocks while keeping the middle one.

Say alloc from step 2 is [ blk1, blk2, blk3], where I have intentionally left out the page info for simplicity. Now the blocks are logical representation based on erlang requirement, where it wants blk2 due to strict alignment requirements. Now it will release blk1 and blk3 while keeping blk2 and use the same. I think that if this is handled correctly, then this should pretty much take care of all use cases (though I didnt spend a lot of time on it though).

**Comment by anttikantee** [comment]
Ah, so it's implementing posix_memalign() by itself.

**Comment by neeraj9** [comment]
Yes. I refrained from even thinking about changing that and instead making erlang align to a page. If you feel that fixing rump will take time then I can go down that path and think whether erlang can live with that alignment for now.

**Comment by anttikantee** [comment]
I'm in the process of fixing partial munmap() (but watching sport at the same time ;)

**Comment by anttikantee** [comment]
This should be fixed now.  If you still run into the problem, please reopen this issue.
