### ISSUE TITLE
trap #UD

### ISSUE THREAD

**Issue by davedoesdev** [rumpkernel/rumprun#52]
I've got Node.js compiling and baking but when I run it, I get

```
trap: #UD
```

in a loop. Any ideas?

**Comment by anttikantee** [comment]
That means your program is trying to execute an invalid opcode.

Can you provide more details on how you built it and how you're trying to run it?

**Comment by anttikantee** [comment]
Pull latest rumprun, and rebuild (with `build-rr.sh`).  Then re-bake your application.  It might print the instruction pointer too (the source line of which you can recover by running gdb on the binary and using `l *value-of-rip`).  "might" because I didn't test it.

Also, you can try attaching a debugger to see if you get a backtrace.

Most likely node.js is using some cpu feature which we don't initialize, shouldn't be too hard to fix.

**Comment by davedoesdev** [comment]
Thanks - I'll try those things. Btw, how do I get a log of the qemu console out?
The notes I've written to myself so far are below. You'll see I've had to work around the lack of `execinfo`.

Assuming rumprun in 'rumprun' directory.

export CC=$PWD/rumprun/app-tools/x86_64-rumprun-netbsd-gcc
export CXX=$PWD/rumprun/app-tools/x86_64-rumprun-netbsd-g++
export AR=$PWD/rumprun/app-tools/x86_64-rumprun-netbsd-ar
export RANLIB=$PWD/rumprun/app-tools/x86_64-rumprun-ranlib
export LINK=$CXX

cp rumprun/{src-netbsd/sys/lib/libunwind/unwind.h,rumprun/include/c++/}

wget https://github.com/nodejs/node/archive/v4.1.1.tar.gz -O - | tar zxf -
wget -r --no-parent http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/lang/nodejs/

export GYP_DEFINES="OS=netbsd"
mkdir -p bin
ln -sf "$(which python)" bin/@PYTHONBIN@
export PATH="$PATH:$PWD/bin"

cd node-4.1.1/
for x in ../ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/lang/nodejs/patches/patch-*; do patch -p0 < "$x"; done

deps/v8/src/base/logging.cc:
  - comment out #include <execinfo.h>
  - comment out body of DumpBacktrace()

deps/v8/tools/gyp/v8.gyp:
  - for 'OS=="netbsd"', replace '-L/usr/pkg/lib -Wl,-R/usr/pkg/lib -lexecinfo' with '-lc++' (-lunwind is added automatically but before -lc++)

deps/openssl/config/opensslconf.h:
  - Add ' || defined(__NetBSD__)' to 'defined(__FreeBSD__) || defined(__OpenBSD__)'

./configure --dest-cpu=x64
make
../rumprun/app-tools/rumpbake hw_generic out/Release/node{.bin,}

Then to run:

../rumprun/app-tools/rumprun kvm -i out/Release/node.bin

---
These are already done in the netbsd nodejs patches:
deps/v8/src/base/platform/platform-posix.cc, add #define PTHREAD_STACK_MIN (size_t)sysconf(_SC_THREAD_STACK_MIN)
deps/v8/src/base/platform/platform-posix.cc, add (char*) to name in pthread_setname_np call

**Comment by davedoesdev** [comment]
```
cannot handle page request order 14!

# Fatal error in heap setup
# Allocation failed - process out of memory
# 

FATAL TRAP: invalid opcode at 0x8 (0x0)
```

Doesn't matter how much memory I give it with `-M`

**Comment by anttikantee** [comment]
A bit of stuff in there.  Are you planning on contributing the build to rumprun-packages?  If you'd provide a branch where it builds but doesn't work, I could look further.

I did check out v8, and it seems like it does all kinds of floating point and sse thingies, so probably the problem lies somewhere in there.  (we don't currently, for example, save floating point registers on context switch ... mostly because I hate floating point ;-)

Bleeding edge new rumprun has serial output support, which you can *currently* use by adding `-g '-vga none -nographic` to your rumprun command line, but don't count on it remaining that way.  You should just be able to copypaste the console output from your console terminal with that.

**Comment by davedoesdev** [comment]
Thanks for the serial output tip.

```
=== calling "out/Release/node.bin" main() ===

rumprun: call to ``_sys___sigprocmask14'' ignored
rumprun: call to ``sigaction'' ignored

#
# Fatal error in heap setup
# Allocation failed - process out of memory
#

FATAL TRAP: invalid opcode at 0x8 (0x0)
```

**Comment by anttikantee** [comment]
Why is the second output missing "cannot handle page request order 14!" ?

**Comment by davedoesdev** [comment]
Don't have a branch yet - working on it. Run with:

```
../rumprun/app-tools/rumprun kvm -M 2048 -g '-vga none -nographic' -i out/Release/node.bin
```

**Comment by davedoesdev** [comment]
I'm not getting the `cannot handle page request order 14!` when I use `-M 2048`

**Comment by anttikantee** [comment]
But you are still getting "process out of memory"?

**Comment by davedoesdev** [comment]
Yes:

```
david@david-Latitude-E6440:~/rumpnode/node-4.1.1$ ../rumprun/app-tools/rumprun kvm -M 2048 -g '-vga none -nographic' -i out/Release/node.bin

!!!
!!! NOTE: rumprun is experimental. syntax may change in the future
!!!

rump kernel bare metal bootstrap

WARNING: Processor claims to not support invariant TSC.
x86_initclocks(): TSC frequency estimate is 2595022270 Hz
Copyright (c) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
    2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015
    The NetBSD Foundation, Inc.  All rights reserved.
Copyright (c) 1982, 1986, 1989, 1991, 1993
    The Regents of the University of California.  All rights reserved.

NetBSD 7.99.17 (RUMP-ROAST)
total memory = 1015 MB
timecounter: Timecounters tick every 10.000 msec
timecounter: Timecounter "clockinterrupt" frequency 100 Hz quality 0
cpu0 at thinair0: rump virtual cpu
root file system type: rumpfs
kern.module.path=/stand/amd64/7.99.17/modules
mainbus0 (root)
pci0 at mainbus0 bus 0
pci0: i/o space, memory space enabled, rd/line, rd/mult, wr/inv ok
vendor 8086 product 1237 (host bridge, revision 0x02) at pci0 dev 0 function 0 not configured
vendor 8086 product 7000 (ISA bridge) at pci0 dev 1 function 0 not configured
vendor 8086 product 7010 (IDE mass storage, interface 0x80) at pci0 dev 1 function 1 not configured
vendor 8086 product 7113 (miscellaneous bridge, revision 0x03) at pci0 dev 1 function 3 not configured
timecounter: Timecounter "bmktc" frequency 1000000000 Hz quality 100
vendor 8086 product 1237 (host bridge, revision 0x02) at pci0 dev 0 function 0 not configured
vendor 8086 product 7000 (ISA bridge) at pci0 dev 1 function 0 not configured
vendor 8086 product 7010 (IDE mass storage, interface 0x80) at pci0 dev 1 function 1 not configured
vendor 8086 product 7113 (miscellaneous bridge, revision 0x03) at pci0 dev 1 function 3 not configured
mounted tmpfs on /tmp

=== calling "out/Release/node.bin" main() ===

rumprun: call to ``_sys___sigprocmask14'' ignored
rumprun: call to ``sigaction'' ignored

#
# Fatal error in heap setup
# Allocation failed - process out of memory
#

FATAL TRAP: invalid opcode at 0x8 (0x0)
```

**Comment by anttikantee** [comment]
Any chance you can put a breakpoint at `i::V8::FatalProcessOutOfMemory` and get a stack trace?

**Comment by anttikantee** [comment]
Actually, brekapoint not that useful, it's coming from the only place with the v8 string "heap setup" ;-)

**Comment by davedoesdev** [comment]
Probably not today but I'll pick it up when I can. If you follow those instructions you should be able to compile if you like.

**Comment by davedoesdev** [comment]
I should break in `Heap::SetUp` really

**Comment by anttikantee** [comment]
Yea, probably there, if only to figure out where the code is.  C++ is lovely to try to understand by reading it.

**Comment by anttikantee** [comment]
ah, it's in heap.cc.  I was blind when I grepped there for the first time

**Comment by davedoesdev** [comment]
Towers of abstraction :)

**Comment by anttikantee** [comment]
In your instructions, why are you highlighting "These are already done in the netbsd nodejs patches:" ?

**Comment by davedoesdev** [comment]
Sorry, that was left over and redundant
Should be deleted/ignored

**Comment by davedoesdev** [comment]
I've built a debug version of node (`--debug` when configuring). When I get time, I'll see if I can get gdb to play ball.

**Comment by anttikantee** [comment]
Why's the python bit required?

The rumprun toolchain should use -g by default.

**Comment by anttikantee** [comment]
err, no, sorry, it uses -g only for the system bits

**Comment by anttikantee** [comment]
`comment out #include `

comment out include what?  all of them?

**Comment by anttikantee** [comment]
I don't see `-g` at least on the command line flags even though I ran configure with `--debug`

**Comment by anttikantee** [comment]
re: floating point registers. We don't actually need to save them, because they are all caller-saved and we never do a context switch without a function call.  So it works out pretty sweet ;-)

**Comment by anttikantee** [comment]
Had to also comment out call to `DumpBacktrace()` in logging.cc.

**Comment by anttikantee** [comment]
The `-I/usr/pkg/include` in deps/v8/build/toolchain.gypi is wrong for Rumprun (arguably it's wrong even for NetBSD, but I don't want to get into that discussion).

**Comment by anttikantee** [comment]
Ok, so v8 has some own weird builtin memory management, where it apparently attempts to ... well, I have no idea what it attempts to do and if the implementations just think they're doing something useful by doing essentially nop calls.  Anyway, the problem for Rumprun is that we explicitly return an error for `mmap(MAP_FIXED)` since we don't have any way of allocating memory at a specific address.  Guess we could check if the memory range is already allocated and return success -- v8 is trying to allocate already allocated memory -- but I don't want to go there now.

Anyway, after commenting out the useless code (specifically the `mmap(MAP_FIXED)` call in platform/platform-openbsd.cc), I get a bit further:

```
> 
Error: Could not get the home directory.
REPL session history will not be persisted.
> kqueue_register: event not supported for file type -1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read EBADF
    at exports._errnoException (util.js:837:11)
    at TTY.onread (net.js:544:26)
```

I'm guessing that's because there's no real TTY on fd 0 on Rumprun.  Maybe you'll know how to use node.js it trying to read stdin.  (though, like I said, a guess, so problem might be entirely elsewhere)

**Comment by davedoesdev** [comment]
Python bit's required because it calls `@PYTHON@`  and I was too lazy to figure out what substitution system it's using. 

Just comment out "#include <execinfo.h>" in `logging.cc`.
My instructions said "comment out body of DumpBacktrace()" in `logging.cc`

**Comment by davedoesdev** [comment]
Thanks for tracking this down. Node runs without stdin by giving it a file to run with.
Can you bundle files with the program using `rumpbake`?
Alternatively, there is a compile option for Node which can do that but I've never used it. I'll take a look.

**Comment by davedoesdev** [comment]
Did you just `return true` from `VirtualMemory::CommitRegion` and `VirtualMemory::UncommitRegion`?

**Comment by davedoesdev** [comment]
Trying to figure out why it's doing this. I found this https://strongloop.com/strongblog/node-js-performance-garbage-collection/

>Large-object-space: Contains objects which are larger than the size limits of other spaces. Each object gets its own mmap’d region of memory. Large objects are never moved by the garbage collector.

**Comment by davedoesdev** [comment]
Another link: https://github.com/nodejs/node-v0.x-archive/issues/4010

**Comment by davedoesdev** [comment]
It's doing `MAP_NORESERVE` then `MAP_FIXED`.
I guess it's trying to get away without reserving space then allocate as much as is desited.
What does rump do with `MAP_NORESERVE`?

**Comment by anttikantee** [comment]
The current easiest way to include files is to put the files you want into an iso (with genisoimage) or an ext2 image (with genext2fs) and give "-b image,/mountpoint" to the rumprun command line.

**Comment by anttikantee** [comment]
Yea just return true from CommitRegion.  I didn't hit an UncommitRegion problem yet (though it might be that that's why I needed -M 2048 to get things going ;-).  Anyway, the whole memory allocation needs to be scrutinized to get things running smoothly, perhaps by writing platform-rumprun.

What `MAP_NORESERVE` does (where it's actually implemented), is to control overcommitting memory.  So unlike allocations without `MAP_NORESERVE`, your process might get a segmentation violation if you write to a page which was allocated with `MAP_NORESERVE` (on an OS with virtual memory, at any rate ;-).  The `MAP_FIXED` bit is essentially just remove the `MAP_NORESERVE` bit from memory areas (and Uncommit adds it back).  So if you have a non-overcommitting VM subsystem, you might see some benefit if you map a lot of memory in the "hey I need to know where I'd put these objects if I ever need them", and then actually never need to allocate those objects.

So, it doesn't matter what `MAP_NORESERVE` does, it matters that `MAP_FIXED` implies adjusting the parameters of that allocation.

Hmm, hmm, I don't immediately know how to fix that smartly without writing a VM subsystem.  If you assume a 1:1 VA:PA mapping (like we have in Rumprun), once you give out a pointer, that physical memory is allocated.  Maybe need to observe the actual allocation behaviour first.

I didn't really find anything which would explain specifically the above from the links, though admittedly I spent only a minute skimming them.

**Comment by anttikantee** [comment]
Ok had to try it.  With this program:

```
pooka@watou:~/temp$ cat dir/hello.js 
console.log('hello, rumpnodejs');
```

and this command:

```
rumprun kvm -M 2048 -g '-vga none -nographic' -i -b ../hello.iso,/hello -D 1234 out/Release/node.bin  /hello/hello.js
```

I get:

```
=== calling "out/Release/node.bin" main() ===

rumprun: call to ``_sys___sigprocmask14'' ignored
rumprun: call to ``sigaction'' ignored
hello, rumpnodejs
FATAL TRAP: general protection at 0x367f1b (0x0)
```

So you can run stuff, just not stop running it ;-)

It dies in the page allocator.  Guess need to have a closer look, though would be nice to figure out how to repro without node.js (since debugging it is rather inconvenient due to the enormous size of the C++ debugging binaries ... my poor machine has only 3GB RAM).

**Comment by anttikantee** [comment]
Exit problem should be fixed now.  Pull in latest rumprun, re-build (typing "make" in platform/hw is enough), rebake node and test:

```
=== calling "out/Release/node.bin" main() ===

rumprun: call to ``_sys___sigprocmask14'' ignored
rumprun: call to ``sigaction'' ignored
hello, rumpnodejs

=== main() of "out/Release/node.bin" returned 0 ===

=== _exit(0) called ===
rump kernel halting...
[...]
```

I really encourage you to contribute your work to rumprun-packages.

**Comment by davedoesdev** [comment]
Thanks - I'll give it a try. I'm trying to get Node's own file bundling facility working.
What does commenting out the `MAP_FIXED` mean in practice?
Does it just mean we'll end up allocating more memory up-front?

**Comment by davedoesdev** [comment]
@anttikantee how are you marshalling arguments to the app in the guest?
I've bundled up a file (`rumptest.js`) into the `node` binary and am trying to run it using:

```shell
../rumprun/app-tools/rumprun kvm -M 2048 -g '-vga none -nographic' -i out/Release/node.bin -e 'require("rumptest")()'
```

But I get an error in the guest:

```
rumprun: no match for key "rumptest")()""
```

If I swap the quotes then I get:

```
require(rumptest)
        ^

ReferenceError: rumptest is not defined
    at [eval]:1:9
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:434:26)
    at node.js:566:27
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by davedoesdev** [comment]
Actually it turns out there's a cleaner way. Put your Javascript into a file called `_third_party_main.js`.

Then configure node with `./configure --dest-cpu=x64 --link-module=_third_party_main.js`

Then bake and run. The script should be run (it's bundled into the executable).

**Comment by davedoesdev** [comment]
You can also repeat `--link-module` multiple times to bundle multiple scripts into the executable. They'll all be available via `require()`'.
There's plenty of JS packaging tools out there which can take a modular app and bundle it all up into a single script.

**Comment by anttikantee** [comment]
On 02/10/15 20:38, David Halls wrote:
> What does commenting out the `MAP_FIXED` mean in practice?
> Does it just mean we'll end up allocating more memory up-front?

That's my theory.  But my theory is based on imagining what such a 
method of memory allocation would try to accomplish.  So I'm not 100% 
sure.  Sometimes people are creative ;)

**Comment by davedoesdev** [comment]
I'll try to get all this converted into a build script for `rumprun-packages`, can't promise when.

**Comment by anttikantee** [comment]
On 02/10/15 20:45, David Halls wrote:
> @anttikantee how are you marshalling arguments to the app in the guest?
> I've bundled up a file (`rumptest.js`) into the `node` binary and am trying to run it using:
>
> ```shell
> ../rumprun/app-tools/rumprun kvm -M 2048 -g '-vga none -nographic' -i out/Release/node.bin -e 'require("rumptest")()'
> ```
>
> But I get an error in the guest:
>
> ```
> rumprun: no match for key "rumptest")()""
> ```
>
> If I swap the quotes then I get:
>
> ```
> require(rumptest)
>          ^

One of the many weaknesses of the rumprun tool is that the arguments get 
randomly evaluated.  And then they get re-parsed into argv at runtime. 
So various forms of quoting and other related lossage occurs.

You can try "rumprun -D kvm ....".  If you find some quotes missing, 
madly add escapes until you see the result you want.  (really sorry 
about that, the launching procedure is just not yet acceptable)

**Comment by anttikantee** [comment]
On 02/10/15 21:05, David Halls wrote:
> I'll try to get all this converted into a build script for `rumprun-packages`, can't promise when.

Awesome, thanks!  Shouldn't take more than half an hour (+build wait). 
I could do it too, but I think you should get the "git annotate" credit 
for your work.

**Comment by anttikantee** [comment]
On 02/10/15 21:05, David Halls wrote:
> I'll try to get all this converted into a build script for `rumprun-packages`, can't promise when.

btw, re: @PYTHONBIN@

https://twitter.com/anttikantee/status/649727469172432896

You need s/\@PYTHONBIN...

I ran that on an otherwise fully patched tree when I hit the @PYTHONBIN@ 
build failure.  Then, after some judiciously voluminous cursing, I 
started from scratch ;-)

**Comment by davedoesdev** [comment]
I'll use `sed -i` or something.
Just looking through the other platform files in v8 to see how they do the memory commit.
Is there a roadmap for rumprun?

**Comment by anttikantee** [comment]
Note that `sed -i` isn't portable (ironically, perl is).

I don't think any of the those platforms are without virtual memory.  If you VM overcommits, you may just run into the situation where the OOM killer needs to run.  However, actual memory allocation is still done when you first fault into the pages, not when you allocate them.

What type of roadmap are you looking for?  There's a very high level one in the annual "rump kernel status report".

**Comment by davedoesdev** [comment]
`ed` then.

Any plans for an equivalent of OSv's Capstan?

**Comment by anttikantee** [comment]
On 02/10/15 21:23, David Halls wrote:
> `ed` then.

Or, you can just replace @PYTHONBIN@ before you add the patches to 
rumprun-packages...

> Any plans for an equivalent of OSv's Capstan?

Can you be more specific?  How does "capstan run" work for example for 
Amazon EC2?  I imagine it doesn't work at all for an embedded system.

The problem with Rumprun is that the scope is much wider than a cloud OS 
for a bunch of hypervisors ("because we can").  So the roadmap for 
Rumprun is to build a platform which allows you to build all kinds of 
useful things for systems in a narrower scope.  There's actually an 
ongoing mailing list thread on this subject.  IMO we made some mistakes 
with a too narrow scope, and at least I am trying to get them fixed now.

**Comment by davedoesdev** [comment]
> Can you be more specific?  How does "capstan run" work for example for Amazon EC2?  I imagine it doesn't work at all for an embedded system.

No idea! If you're thinking about these things then fair enough.

Another question: for `qemu`/`kvm`, are you able to use [qboot](https://lwn.net/Articles/645455/)?

I did some rough measurements by adding `-nographic -S` to the command line, pressing 'Ctrl-A c' to get to the monitor, then 'Ctrl-A t' to turn on timestamps then typing 'c' and finally Enter.

For standard BIOS until first kernel message this gave 0.989, 0.932, 0.988 (average: 0.969)
For qboot BIOS (fw_cfg): 0.895, 0.887, 0.835 (average: 0.872)
cbfs timings: 0.688 0.597 0.643 (average: 0.642)

This was unmodified Ubuntu 14.10 qemu.

I built the cbfs image per the qboot README:

```shell
dd if=/dev/zero of=boot.bin bs=4096 count=1
../coreboot-HEAD-44cbe10/util/cbfstool/cbfstool cbfs.rom create -s 8128k -B boot.bin -m x86 -o 0x1000
../coreboot-HEAD-44cbe10/util/cbfstool/cbfstool cbfs.rom add -f ~/Downloads/aboriginal-1.4.1/build/system-image-x86_64/linux -n vmlinuz -t raw
echo 'console=ttyS0' > cmdline
../coreboot-HEAD-44cbe10/util/cbfstool/cbfstool cbfs.rom add -f cmdline -n cmdline -t raw
```

and then ran with:

```shell
qemu-system-x86_64 -nographic -drive if=pflash,file=bios.bin,readonly=on -drive if=pflash,file=cbfs.rom,readonly=on -no-reboot -S
```

Another way of doing the timing is as @bonzini suggests:

>I compiled qboot with -DBENCHMARK_HACK and added "-device isa-debug-exit,iobase=0xf4" to the QEMU command line. Then you can just us "time" from the shell.

**Comment by davedoesdev** [comment]
`platform-aix.cc` does something a bit different.

**Comment by davedoesdev** [comment]
I think the memory allocation needs fixing - it fails with less than 2G of RAM!

**Comment by davedoesdev** [comment]
Probably the best thing to do is have an option which limits the amount of memory V8 grabs in its initial `mmap`.

**Comment by davedoesdev** [comment]
```
    // When a target requires the code range feature, we put all code objects
    // in a kMaximalCodeRangeSize range of virtual address space, so that
    // they can call each other with near calls.
```

**Comment by davedoesdev** [comment]
My proposal is in `CodeRange::SetUp()` (`heap/spaces.cc`), instead of failing first time if `code_range_->IsReserved()` is false, loop round and try again with half the requested size. Repeat until we get down to `kMinimumCodeRangeSize`.

**Comment by anttikantee** [comment]
On 03/10/15 07:34, David Halls wrote:
> My proposal is in `CodeRange::SetUp()` (`heap/spaces.cc`), instead of failing first time if `code_range_->IsReserved()` is false, loop round and try again with half the requested size. Repeat until we get down to `kMinimumCodeRangeSize`.

Isn't it simpler to limit kMaximalCodeRangeSize to something sensible 
like 16MB and document that limit?  With the halving approach you might 
accidentally allocate nearly all of the memory available to the 
instance, and it's rather non-obvious how much more memory you need to 
give, since the consumption increases if you give more memory.

**Comment by davedoesdev** [comment]
I'm not sure it allocates any more on demand. I _think_ it allocates all this virtual mem and then fixes chunks out of it. Probably making this configurable is the best way to do it.

**Comment by anttikantee** [comment]
On 03/10/15 11:51, David Halls wrote:
> I'm not sure it allocates any more on demand. I _think_ it allocates all this virtual mem and then fixes chunks out of it. Probably making this configurable is the best way to do it.

Yes I wouldn't expect it to allocate more.

Sure, you can make it launch-time configurable instead of compile-time 
configurable if you want to.

**Comment by davedoesdev** [comment]
Ah, maybe I need to adjust to the rumprun mindset. Do all deployment options support launch-time configuration?

**Comment by anttikantee** [comment]
On 03/10/15 12:59, David Halls wrote:
> Ah, maybe I need to adjust to the rumprun mindset. Do all deployment options support launch-time configuration?

Yes, Rumprun always processes a config file.  That config file is 
specified *earliest* around the time that the binary is linked (and in 
some scenariors later).

However, what I'd do is:
1) hardcode a sensible codesize limit (maybe 16MB is even too much?)
2) check that a few non-trivial node.js programs work
3) package and announce the package
4) file a separate issue in rumprun-packages for the memory allocation 
enhancements

It's always good to give others the option to collaborate.  There's no 
guarantee that others will be immediately chipping in, but if you don't 
publish there's a guarantee that others won't help.

**Comment by davedoesdev** [comment]
I'll hardcode the limit in the build script. Will take a day or three.

**Comment by anttikantee** [comment]
On 03/10/15 13:10, David Halls wrote:
> I'll hardcode the limit in the build script. Will take a day or three.

Looking forward to seeing the result in a day or three (but not two!).

**Comment by davedoesdev** [comment]
Turns out a judicial call to `params.constraints.set_code_range_size` in `StartNodeInstance` does the job

**Comment by davedoesdev** [comment]
https://github.com/rumpkernel/rumprun-packages/pull/16

**Comment by anttikantee** [comment]
I thought we agreed on 1 or 3 days, not 2!
oh well, i'll let it slide this time ;-)

**Comment by anttikantee** [comment]
Original issue fixed and, as indicated above, superseded by rumpkernel/rumprun-packages#16.
