### ISSUE TITLE
Windows userspace support without Cygwin

### ISSUE THREAD

**Issue by 6D65** [rumpkernel/rumprun#53]
Hi,

The documentation says that it's possible to run RumpKernels in userspace for various OS's(https://github.com/rumpkernel/wiki/wiki/Platforms) including Windows through Cygwin.

Cygwin is nice, though I wonder if you're planning to add support for non POSIX OS's like Windows.

Thanks

**Comment by anttikantee** [comment]
On 03/10/15 11:25, The Dude wrote:
> The documentation says that it's possible to run RumpKernels in userspace for various OS's(https://github.com/rumpkernel/wiki/wiki/Platforms) including Windows through Cygwin.
>
> Cygwin is nice, though I wonder if you're planning to add support for non POSIX OS's like Windows.

This question would be better asked on the mailing list, but ...

The Rumprun stack runs on top of a very small non-POSIX OS called "bmk", 
and the rump kernel in the Rumprun stack also runs on top that non-POSIX 
bmk OS.

No, I am not aware of anyone planning to add winapi support.

**Comment by anttikantee** [comment]
btw, you might want to check out http://wiki.rumpkernel.org/Info:-FAQ and http://wiki.rumpkernel.org/Repo#the-big-picture

I guess I should update the "Platforms" page too.

**Comment by 6D65** [comment]
Cool, thank you.

So, what I was thinking about is that rumpkernel seems like an ideal candidate for a tool like Vagrant/otto. Basically having the ability to choose to run the same image on a KVM/Xen/VirualBox backend and at the same time run the kernel in user space for development, ideally everything working out of the box, with less overhead then spinning up(and downloading) a full VM.

So a big differentiator for rumpkernel would be that it's much easier to develop apps against, and at the end the apps would have a minimal overhead in production. I hope it makes sense.

**Comment by anttikantee** [comment]
Well, first of all, running Rumprun in userspace and running just a rump kernel in userspace are different things.

For rump kernels it sort of makes sense for when you are building applications which kernel drivers as libraries (TCP/IP for DPDK, file system drivers for mtools-worksalikes, etc.).  However, those really are userspace applications which just use kernel drivers as libraries.

For the entire Rumprun stack it does not make quite as much sense, since first of all it's really easy to run the entire stack with KVM/QEMU (did you try it?).  Second of all, since you're developing a normal "userspace" application (which you just happen to be able to run on a unikernel), *DEVELOP IT IN USERSPACE* ;-)
So the only main difference comes from bundling, but those you need to test on the final target anyway.  If you want to be really supersure that everything is the same, I'd install NetBSD and run the application under development against the Rumprun libc.

Remember, I started rump kernels as a method for developing kernel drivers as userspace programs, so the whole convenience factor is really close to my heart.  I just don't see much of it here.

Anyway, if you have more questions, please take it to the mailing list.

**Comment by justincormack** [comment]
See https://github.com/justincormack/frankenlibc/issues/5 if you want to run unikernels in userspace.
